// <auto-generated />
using System;
using HalisPeynir.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HalisPeynir.Migrations
{
    [DbContext(typeof(HalisPeynirDBContext))]
    partial class HalisPeynirDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HalisPeynir.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"), 1L, 1);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenderID")
                        .HasColumnType("int");

                    b.Property<int>("JobTitleID")
                        .HasColumnType("int");

                    b.Property<string>("NameAndSecName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("ShiftID")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("WorkStatus")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeID");

                    b.HasIndex("GenderID");

                    b.HasIndex("JobTitleID");

                    b.HasIndex("ShiftID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            DOB = new DateTime(2001, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderID = 1,
                            JobTitleID = 1,
                            NameAndSecName = "Bob",
                            ShiftID = 1,
                            Surname = "Taylor",
                            WorkStatus = true
                        },
                        new
                        {
                            EmployeeID = 2,
                            DOB = new DateTime(2002, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderID = 2,
                            JobTitleID = 2,
                            NameAndSecName = "Michael",
                            ShiftID = 2,
                            Surname = "Blanch",
                            WorkStatus = false
                        },
                        new
                        {
                            EmployeeID = 3,
                            DOB = new DateTime(2006, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenderID = 3,
                            JobTitleID = 3,
                            NameAndSecName = "Leyla",
                            ShiftID = 3,
                            Surname = "Green",
                            WorkStatus = true
                        });
                });

            modelBuilder.Entity("HalisPeynir.Models.Gender", b =>
                {
                    b.Property<int>("GenderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderID"), 1L, 1);

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("GenderID");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderID = 1,
                            GenderName = "Female"
                        },
                        new
                        {
                            GenderID = 2,
                            GenderName = "Male"
                        },
                        new
                        {
                            GenderID = 3,
                            GenderName = "I don't wanna choose"
                        });
                });

            modelBuilder.Entity("HalisPeynir.Models.JobTitle", b =>
                {
                    b.Property<int>("JobTitleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTitleID"), 1L, 1);

                    b.Property<string>("JobTitleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("JobTitleID");

                    b.ToTable("JobTitles");

                    b.HasData(
                        new
                        {
                            JobTitleID = 1,
                            JobTitleName = "Techinician"
                        },
                        new
                        {
                            JobTitleID = 2,
                            JobTitleName = "Master"
                        },
                        new
                        {
                            JobTitleID = 3,
                            JobTitleName = "Director"
                        });
                });

            modelBuilder.Entity("HalisPeynir.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Name = "Ezine Sert 600 gr",
                            Price = 60m
                        },
                        new
                        {
                            ProductID = 2,
                            Name = "Ezine Sert 350 gr",
                            Price = 20m
                        },
                        new
                        {
                            ProductID = 3,
                            Name = "Ezine Sert 150 gr",
                            Price = 15m
                        },
                        new
                        {
                            ProductID = 4,
                            Name = "Ezine Sert 400 gr",
                            Price = 50m
                        });
                });

            modelBuilder.Entity("HalisPeynir.Models.Servicee", b =>
                {
                    b.Property<int>("ServiceeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceeID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ServiceeID");

                    b.ToTable("Servicees");

                    b.HasData(
                        new
                        {
                            ServiceeID = 1,
                            Name = "Service 1",
                            Price = 70m
                        },
                        new
                        {
                            ServiceeID = 2,
                            Name = "Service 2",
                            Price = 40m
                        },
                        new
                        {
                            ServiceeID = 3,
                            Name = "Service 3",
                            Price = 55m
                        },
                        new
                        {
                            ServiceeID = 4,
                            Name = "Service 4",
                            Price = 90m
                        });
                });

            modelBuilder.Entity("HalisPeynir.Models.Shift", b =>
                {
                    b.Property<int>("ShiftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftID"), 1L, 1);

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ShiftID");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            ShiftID = 1,
                            ShiftName = "Morning"
                        },
                        new
                        {
                            ShiftID = 2,
                            ShiftName = "Evening"
                        },
                        new
                        {
                            ShiftID = 3,
                            ShiftName = "Night"
                        });
                });

            modelBuilder.Entity("HalisPeynir.Models.Employee", b =>
                {
                    b.HasOne("HalisPeynir.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HalisPeynir.Models.JobTitle", "JobTitle")
                        .WithMany()
                        .HasForeignKey("JobTitleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HalisPeynir.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("JobTitle");

                    b.Navigation("Shift");
                });
#pragma warning restore 612, 618
        }
    }
}
